builds:
  -
    id: "dnscache"
    binary: dnscache
    main: ./cmd/dnscache/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: dnscache-binaries
    name_template: "dnscache-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "dnscache_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/dnscache
    maintainer: Michael Paepcke <git@paepcke.de>
    description: dnscache
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
